services:
      rebecca-mysql:
            image: mysql:8.0
            container_name: rebecca-mysql
            restart: on-failure:5
            ports:
                  - "${MYSQL_LOCAL_PORT}:3306"
            volumes:
                  - mysql-data:/var/lib/mysql
                  - ./doc/docker/mysql/init.d:/docker-entrypoint-initdb.d
                  - ./doc/docker/mysql/mysql.cnf:/etc/mysql/my.cnf
            environment:
                  MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
                  TZ: ${TZ}
            command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
#            healthcheck:
#                  test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
#                  interval: 10s
#                  timeout: 5s
#                  retries: 3
#                  start_period: 30s
            networks:
                  - app

      rebecca-redis:
            image: redis:3.2
            platform: linux/amd64
            ports:
                  - "${REDIS_LOCAL_PORT}:6379"
            restart: on-failure:5
            container_name: rebecca-redis
            volumes:
                  - ./doc/docker/redis/redis.conf:/usr/local/etc/redis/redis.conf:rw
                  - redis-data:/data  # 用于持久化 Redis 数据
            command: /bin/bash -c "redis-server /usr/local/etc/redis/redis.conf --requirepass $REDIS_PASSWORD"
            networks:
                  - app

      rebecca-nacos:
            image: nacos/nacos-server:v2.1.0
            platform: linux/amd64
            container_name: rebecca-nacos
            environment:
                  - MODE=standalone
                  - PREFER_HOST_MODE=hostname
#                  - SPRING_DATASOURCE_PLATFORM=mysql ????????????????浪费我两个点 6
                  - MYSQL_SERVICE_HOST=rebecca-mysql
                  - MYSQL_SERVICE_PORT=3306
                  - MYSQL_SERVICE_USER=root
                  - MYSQL_SERVICE_PASSWORD=${MYSQL_ROOT_PASSWORD}
                  - MYSQL_SERVICE_DB_NAME=nacos
                  - JVM_XMS=128m
                  - JVM_XMX=128m
                  - JVM_XMN=128m
            volumes:
                  - ./doc/docker/nacos/logs:/home/nacos/logs
                  - ./doc/docker/nacos/init.d:/home/nacos/init.d
            ports:
                  - 8848:8848
                  - 9848:9848
                  - 9849:9849
            depends_on:
                  - rebecca-mysql
#                  rebecca-mysql:
#                        condition: service_healthy
            networks:
                  - app

networks:
      app:

volumes:
      mysql-data:
      redis-data: